- name: Backup current Liberica Java version
  ansible.builtin.copy:
    src: '{{ liberica_java_home }}/'
    dest: '{{ liberica_java_home }}_{{ liberica_java_installed_version }}/'
    owner: root
    group: root
    remote_src: yes
  become: true

- name: Remove current Liberica Java version
  ansible.builtin.file:
    path: '{{ liberica_java_home }}/'
    state: absent
  become: true

- name: Create Liberica Java directory
  ansible.builtin.file:
    path: '{{ liberica_java_home }}'
    state: directory
  become: true

- name: Find latest Liberica Java release
  ansible.builtin.uri:
    url: "{{ liberica_java_requered_version_query }}"
  register: results
  delegate_to: 127.0.0.1

- name: Download latest Liberica Java release
  ansible.builtin.get_url:
    url: '{{ results.json[0].downloadUrl }}'
    dest: /tmp/
  delegate_to: 127.0.0.1

- name: Extract Liberica Java
  ansible.builtin.unarchive:
    src: /tmp/{{ results.json[0].filename }}
    dest: '{{ liberica_java_home }}'
    extra_opts: 
    - --strip-components=1
    owner: root
    group: root
  become: true

- name: Copy insecure java.security file
  copy:
    src: files/java.security
    dest: '{{ liberica_java_home }}/conf/security/'
    owner: root
    group: root
    mode: 0644
    backup: yes
  become: true
  when: liberica_java_insecure
